name: Update Scoop Manifests and README (Python)

on:
  workflow_dispatch: # به شما اجازه می‌ده اکشن رو به صورت دستی از طریق تب Actions در گیت‌هاب اجرا کنید
  schedule:
    - cron: '30 16 * * *' # هر روز ساعت 16:30 UTC (حدوداً ۸ شب به وقت تهران)

jobs:
  update_manifests:
    runs-on: windows-latest # ماشین مجازی ویندوزی

    permissions:
      contents: write # اجازه نوشتن برای کامیت و پوش کردن تغییرات

    steps:
      - name: Checkout Repository # قدم ۱: دانلود کد مخزن شما
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Scoop # قدم ۲: نصب و آماده‌سازی Scoop
        uses: MinoruSekine/setup-scoop@v1
        # پارامتر scoop_branch دیگر پشتیبانی نمی‌شود و حذف شده است

      - name: Set up Python # قدم ۳: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies # قدم ۴: نصب کتابخانه‌های پایتون
        run: |
          python -m pip install --upgrade pip
          pip install requests
        shell: pwsh

      - name: Run Python script to update manifests # قدم ۵: اجرای اسکریپت پایتون شما
        id: run_update_script
        env:
          PYTHONIOENCODING: UTF-8 # <--- این خط برای حل مشکل انکودینگ در خروجی پایتون اضافه شده
          GITHUB_REPOSITORY: ${{ github.repository }} # برای دسترسی اسکریپت به نام ریپازیتوری
        run: python update_manifests.py # فرض بر این است که اسکریپت در ریشه ریپازیتوری قرار دارد
        shell: pwsh

      - name: Commit and Push Changes # قدم ۶: کامیت و پوش کردن تغییرات
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if ! git diff --quiet HEAD; then
            echo "Changes detected, committing and pushing..."
            git add bucket/*.json README.md 
            git commit -m "Automated: Update app manifests and README (Python)"
            git push
          else
            echo "No changes to commit."
          fi
        shell: bash