name: Update Scoop Bucket (Two Python Scripts)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 4 * * *' # Runs daily at 04:00 UTC

jobs:
  update_bucket_and_readme:
    name: Update Manifests, Hashes, and README
    runs-on: windows-latest

    permissions:
      contents: write # Needed to commit changes back to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Python dependencies
        shell: pwsh
        run: |
          Write-Host "[INFO] Installing Python dependencies..."
          python -m pip install --upgrade pip
          pip install requests packaging # 'packaging' is needed by Update-AppVersionsAndUrls.py
          Write-Host "[SUCCESS] Python dependencies installed."

      - name: Run Python script to Update App Versions and URLs
        id: update_versions_urls
        shell: pwsh
        env:
          PYTHONIOENCODING: UTF-8
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_API_TOKEN_SCOOP_UPDATER: ${{ secrets.YOUR_REPO_PAT }} # IMPORTANT: Create this secret in your repo
        run: |
          Write-Host "[INFO] Running Python script Update-AppVersionsAndUrls.py..."
          python ./Update-AppVersionsAndUrls.py 
          Write-Host "[SUCCESS] Update-AppVersionsAndUrls.py script finished."

      - name: Run Python script to Update Hashes and README
        id: update_hashes_readme
        shell: pwsh
        env:
          PYTHONIOENCODING: UTF-8
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          Write-Host "[INFO] Running Python script Update-HashesAndReadme.py..."
          python ./Update-HashesAndReadme.py 
          Write-Host "[SUCCESS] Update-HashesAndReadme.py script finished."

      - name: Commit and Push Changes
        shell: bash
        run: |
          echo "[INFO] --- Starting Commit and Push ---"
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "[INFO] Git Status Before Add:"
          git status
          
          git add bucket/*.json README.md
          
          echo "[INFO] Git Status After Add (Before Commit):"
          git status

          if ! git diff --cached --quiet; then
            echo "[ACTION] Changes detected and staged. Committing and pushing..."
            git commit -m "Automated: Update app versions, URLs, hashes, and README"
            git push
            echo "[SUCCESS] Changes committed and pushed."
          else
            echo "[INFO] No staged changes to commit."
          fi
          echo "[INFO] --- Commit and Push Finished ---"
