name: Update Scoop Bucket (Multi-Script)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '30 16 * * *' # Daily at 16:30 UTC (approx 8 PM Tehran time)

jobs:
  update_bucket_files:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to commit changes back to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Scoop
        uses: MinoruSekine/setup-scoop@v1

      - name: Add Scoop shims to PATH (for subsequent PowerShell steps)
        run: echo "$HOME\scoop\shims" | Add-Content -Path $env:GITHUB_PATH
        shell: pwsh

      - name: Update Scoop and add/update essential buckets
        run: |
          scoop update scoop
          scoop bucket add main # Ensure main bucket is present
          scoop bucket add extras # Extras bucket often contains useful utilities
          scoop update # Update all buckets
        shell: pwsh
        continue-on-error: true # Continue if a bucket add fails (e.g. already exists)

      - name: Run PowerShell Script to Update Manifest Versions & URLs
        id: update_versions_urls
        run: ./Update-ScoopVersions.ps1 -BucketPath "./bucket"
        shell: pwsh
        continue-on-error: true # Python script will handle current state

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install requests
        shell: pwsh

      - name: Run Python script to Update Hashes and README
        id: update_hashes_readme
        env:
          PYTHONIOENCODING: UTF-8
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python Update-HashesAndReadme.py
        shell: pwsh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if ! git diff --quiet HEAD; then
            echo "Changes detected, committing and pushing..."
            git add bucket/*.json README.md
            git commit -m "Automated: Update app manifests, hashes, and README"
            git push
          else
            echo "No changes to commit."
          fi
        shell: bash