name: Update Scoop Bucket (Multi-Script)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '30 16 * * *' # Daily at 16:30 UTC

jobs:
  update_bucket_files:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to commit changes back to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GitHub API access for action (Diagnostic)
        shell: pwsh
        run: |
          Invoke-RestMethod -Uri "https://api.github.com/repos/babochka/setup-scoop/releases/tags/v2.0.1" | Select-Object name, tag_name, published_at | Format-List
        continue-on-error: true # Continue even if this diagnostic step fails

      - name: Setup Scoop using babochka/setup-scoop (with commit SHA)
        # Using commit SHA for v2.0.1 to bypass potential tag resolution issues
        uses: babochka/setup-scoop@9babf5750d1f10388009956310791750c618b2a0 
        id: setup_scoop
        # This action automatically adds Scoop to PATH

      - name: Update Scoop itself and core buckets
        shell: pwsh
        run: |
          Write-Host "Updating Scoop and core buckets..."
          scoop update scoop
          scoop bucket rm main -ErrorAction SilentlyContinue
          scoop bucket add main -ErrorAction SilentlyContinue
          scoop bucket rm extras -ErrorAction SilentlyContinue
          scoop bucket add extras -ErrorAction SilentlyContinue
          scoop update # Update all buckets
        continue-on-error: true

      - name: Verify Scoop installation and checkver command
        shell: pwsh
        run: |
          Write-Host "--- Verifying Scoop Installation ---"
          Write-Host "Scoop executable path (from Get-Command):"
          Get-Command scoop.exe -ErrorAction SilentlyContinue | Format-List *
          Write-Host "Scoop Shims Path (from setup_scoop action output): ${{ steps.setup_scoop.outputs.scoop_shims_path }}"
          Write-Host "PATH environment variable:"
          $env:PATH -split ';' | ForEach-Object { Write-Host "  $_" }
          Write-Host "Scoop Version:"
          scoop.exe --version -ErrorAction SilentlyContinue
          Write-Host "Scoop Help (check for checkver):"
          scoop.exe help -ErrorAction SilentlyContinue
          scoop.exe help checkver -ErrorAction SilentlyContinue
          Write-Host "Scoop Status:"
          scoop.exe status -ErrorAction SilentlyContinue
          Write-Host "--- End Verification ---"
        continue-on-error: true

      - name: Run PowerShell Script to Update Manifest Versions & URLs
        id: update_versions_urls
        run: ./Update-ScoopVersions.ps1 -BucketPath "./bucket"
        shell: pwsh
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install requests
        shell: pwsh

      - name: Run Python script to Update Hashes and README
        id: update_hashes_readme
        env:
          PYTHONIOENCODING: UTF-8
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python Update-HashesAndReadme.py
        shell: pwsh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "--- Git Status Before Diff ---"
          git status
          echo "--- End Git Status ---"
          
          if ! git diff --quiet HEAD; then
            echo "Changes detected, committing and pushing..."
            git add bucket/*.json README.md
            git commit -m "Automated: Update app manifests, hashes, and README"
            git push
          else
            echo "No changes to commit."
          fi
        shell: bash
