name: Update Scoop Bucket (Multi-Script)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '30 16 * * *' # Daily at 16:30 UTC

jobs:
  update_bucket_files:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to commit changes back to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Scoop, Update Buckets, and Run Update-ScoopVersions.ps1
        id: scoop_operations
        shell: pwsh
        run: |
          Write-Host "Attempting to install Scoop manually..."
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          $ErrorActionPreference = "Stop" 
          try {
            Invoke-RestMethod -Uri https://get.scoop.sh -OutFile scoop_installer.ps1
          } catch {
            Write-Warning "Invoke-RestMethod failed. Error: $($_.Exception.Message)"
            Write-Host "Trying with Invoke-WebRequest..."
            Invoke-WebRequest -Uri https://get.scoop.sh -OutFile scoop_installer.ps1
          }
          $ErrorActionPreference = "Continue" 

          if (!(Test-Path scoop_installer.ps1)) {
            Write-Error "Scoop installer script (scoop_installer.ps1) not found after download attempt."
            exit 1
          }

          Write-Host "Scoop installer downloaded. Running installer..."
          $env:SCOOP = "$HOME\scoop" 
          if (-not (Test-Path $env:SCOOP)) {
            New-Item -ItemType Directory -Path $env:SCOOP -Force | Out-Null
          }
          .\scoop_installer.ps1 -RunSelfUpdate -ScoopDir $env:SCOOP
          Write-Host "Scoop installation script executed."
          
          $ScoopShimsPath = Join-Path $env:SCOOP "shims"
          Write-Host "Determined Scoop Shims Path: $ScoopShimsPath"
          
          Add-Content -Path $env:GITHUB_PATH -Value $ScoopShimsPath
          Write-Host "Added '$ScoopShimsPath' to GITHUB_PATH (for potential future steps)."

          if ($env:PATH -notlike "*$ScoopShimsPath*") {
            $env:PATH = "$ScoopShimsPath;$env:PATH"
            Write-Host "Added '$ScoopShimsPath' to current session PATH."
          } else {
            Write-Host "'$ScoopShimsPath' was already in current session PATH."
          }
          Write-Host "Current session PATH relevant part: $($env:PATH.Substring(0, [System.Math]::Min($env:PATH.Length, 200)))..."

          Write-Host "Verifying Scoop installation immediately in this session (using 'scoop' command)..."
          scoop --version
          scoop status
          
          Remove-Item scoop_installer.ps1 -Force
          Write-Host "Removed scoop_installer.ps1."

          Write-Host "Listing contents of Scoop shims directory: $ScoopShimsPath (Confirming scoop.ps1 or scoop.cmd exists)"
          Get-ChildItem -Path $ScoopShimsPath | ForEach-Object { Write-Host "  Found in shims: $($_.Name)" }

          Write-Host "Updating Scoop and core buckets..."
          scoop update scoop
          scoop bucket rm main -ErrorAction SilentlyContinue 
          scoop bucket add main
          scoop bucket rm extras -ErrorAction SilentlyContinue 
          scoop bucket add extras
          scoop update 
          Write-Host "Scoop and core buckets update process finished."

          $ScriptPath = "./Update-ScoopVersions.ps1"
          Write-Host "Running PowerShell Script: $ScriptPath with Shims Path parameter '$ScoopShimsPath'"
          if (!(Test-Path $ScriptPath)) {
            Write-Error "Update-ScoopVersions.ps1 not found at $ScriptPath"
            exit 1
          }
          # Pass the determined $ScoopShimsPath to the script
          & $ScriptPath -BucketPath "./bucket" -ProvidedScoopShimsPath $ScoopShimsPath
          if ($LASTEXITCODE -ne 0) {
            Write-Warning "Update-ScoopVersions.ps1 script finished with exit code $LASTEXITCODE."
            # Optionally, exit 1 here if script failure should fail the job
            # exit 1 
          } else {
            Write-Host "Update-ScoopVersions.ps1 script finished successfully."
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install requests
        shell: pwsh

      - name: Run Python script to Update Hashes and README
        id: update_hashes_readme
        env:
          PYTHONIOENCODING: UTF-8
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python Update-HashesAndReadme.py
        shell: pwsh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "--- Git Status Before Add ---"
          git status
          git add bucket/*.json README.md
          echo "--- Git Status After Add (Before Commit) ---"
          git status
          if ! git diff --cached --quiet; then
            echo "Changes detected and staged, committing and pushing..."
            git commit -m "Automated: Update app manifests, hashes, and README"
            git push
          else
            echo "No staged changes to commit."
          fi
        shell: bash
