name: Update Scoop Bucket (Python Only for Hashes/README)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 2 * * *' # Runs daily at 02:00 UTC

jobs:
  update_files_with_python:
    name: Update Hashes and README via Python
    runs-on: windows-latest

    permissions:
      contents: write # Needed to commit changes back to the repository

    steps:
      - name: Checkout Your Bucket Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install Python dependencies
        shell: pwsh
        run: |
          Write-Host "[INFO] Installing Python dependencies..."
          python -m pip install --upgrade pip
          pip install requests # Assuming 'requests' is the only dependency for the Python script
          Write-Host "[SUCCESS] Python dependencies installed."

      - name: Run Python script to Update Hashes and README
        id: update_hashes_readme
        shell: pwsh
        env:
          PYTHONIOENCODING: UTF-8 # Ensures Python handles UTF-8 correctly
          GITHUB_REPOSITORY: ${{ github.repository }} # Provides repo context to Python script
        run: |
          Write-Host "[INFO] Running Python script Update-HashesAndReadme.py..."
          Write-Warning "NOTE: This workflow ONLY updates hashes based on existing URLs in manifests and updates the README."
          Write-Warning "Automatic version and URL updates via 'scoop checkver' are NOT performed by this CI."
          Write-Warning "Please ensure manifest versions and URLs are updated manually before pushing if needed."
          python ./Update-HashesAndReadme.py # Script is expected to be in the repo root
          Write-Host "[SUCCESS] Python script finished."

      - name: Commit and Push Changes
        shell: bash # Using bash for git commands is common
        run: |
          echo "[INFO] --- Starting Commit and Push ---"
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "[DEBUG] Current directory: $(pwd)"
          echo "[INFO] Git Status Before Add:"
          git status
          
          # Add specific files expected to change by the Python script
          git add bucket/*.json README.md
          
          echo "[INFO] Git Status After Add (Before Commit):"
          git status

          # Check if there are staged changes to commit
          if ! git diff --cached --quiet; then
            echo "[ACTION] Changes detected and staged. Committing and pushing..."
            # Modified commit message to reflect the current scope
            git commit -m "Automated: Update app hashes and README (Manual version/URL updates assumed)"
            git push
            echo "[SUCCESS] Changes committed and pushed."
          else
            echo "[INFO] No staged changes to commit."
          fi
          echo "[INFO] --- Commit and Push Finished ---"
